// Code generated by "temporal-gen -type=Activities"; DO NOT EDIT.

package test

import (
	"go.temporal.io/sdk/workflow"
	"encoding/json"
)
type ActivitiesStub struct {
	a *Activities
}

func (s *ActivitiesStub) MarkReadyForUploadsAndGet(ctx workflow.Context, jobID string) (err error) {
	f := workflow.ExecuteActivity(ctx, s.a.MarkReadyForUploads, jobID)
	return f.Get(ctx, nil)
}

func (s *ActivitiesStub) MarkReadyForUploads(ctx workflow.Context, jobID string) workflow.Future {
	f := workflow.ExecuteActivity(ctx, s.a.MarkReadyForUploads, jobID)
	return f
}

func (s *ActivitiesStub) DoSomethingAndGet(ctx workflow.Context, jobID string, i *json.RawMessage) (string, error) {
	f := workflow.ExecuteActivity(ctx, s.a.DoSomething, jobID, i)
	var res string
	return res, f.Get(ctx, &res)
}

func (s *ActivitiesStub) DoSomething(ctx workflow.Context, jobID string, i *json.RawMessage) workflow.Future {
	f := workflow.ExecuteActivity(ctx, s.a.DoSomething, jobID, i)
	return f
}

