// Code generated by "temporal-gen -type=Activities"; DO NOT EDIT.

package test

import (
	"encoding/json"
	"go.temporal.io/sdk/workflow"
)

type ActivitiesStub struct {
	a *Activities
}

func (s *ActivitiesStub) MarkReadyForUploadsExec(ctx workflow.Context, jobID string) (err error) {
	f := workflow.ExecuteActivity(ctx, s.a.MarkReadyForUploads, jobID)
	return f.Get(ctx, nil)
}

func (s *ActivitiesStub) MarkReadyForUploadsStart(ctx workflow.Context, jobID string) workflow.Future {
	f := workflow.ExecuteActivity(ctx, s.a.MarkReadyForUploads, jobID)
	return f
}

func (s *ActivitiesStub) DoSomethingExec(ctx workflow.Context, jobID string, i *json.RawMessage) (string, error) {
	f := workflow.ExecuteActivity(ctx, s.a.DoSomething, jobID, i)
	var _res string
	return _res, f.Get(ctx, &_res)
}

func (s *ActivitiesStub) DoSomethingStart(ctx workflow.Context, jobID string, i *json.RawMessage) workflow.Future {
	f := workflow.ExecuteActivity(ctx, s.a.DoSomething, jobID, i)
	return f
}
